{
  "formatVersion": "1.1",
  "component": {
    "group": "com.corbado.passkeys_android",
    "module": "passkeys_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        }
      ],
      "files": [
        {
          "name": "passkeys_android_release-1.0.aar",
          "url": "passkeys_android_release-1.0.aar",
          "size": 46669,
          "sha512": "76f6020cb5624482e715aa3a95fd4e26904a179d40c4478e4c8fb495f577480182ee71e5d3800ef7a8587af85a55000a272c4b01bc0087871b65048ea576c8af",
          "sha256": "403a88413fa4e37b5f9865ec3bd137705c6c52944d0b8b9f49536e1bb2766cfd",
          "sha1": "32be1d6b14f741576d1c40a3452456db6820282d",
          "md5": "fbbf3c270a6e56b8cad658275daff6ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk7",
          "version": {
            "requires": "1.8.10"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.6.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.credentials",
          "module": "credentials-play-services-auth",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-auth",
          "version": {
            "requires": "20.5.0"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-fido",
          "version": {
            "requires": "20.0.1"
          }
        },
        {
          "group": "androidx.multidex",
          "module": "multidex",
          "version": {
            "requires": "2.0.1"
          }
        }
      ],
      "files": [
        {
          "name": "passkeys_android_release-1.0.aar",
          "url": "passkeys_android_release-1.0.aar",
          "size": 46669,
          "sha512": "76f6020cb5624482e715aa3a95fd4e26904a179d40c4478e4c8fb495f577480182ee71e5d3800ef7a8587af85a55000a272c4b01bc0087871b65048ea576c8af",
          "sha256": "403a88413fa4e37b5f9865ec3bd137705c6c52944d0b8b9f49536e1bb2766cfd",
          "sha1": "32be1d6b14f741576d1c40a3452456db6820282d",
          "md5": "fbbf3c270a6e56b8cad658275daff6ac"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "passkeys_android_release-1.0-sources.jar",
          "url": "passkeys_android_release-1.0-sources.jar",
          "size": 15103,
          "sha512": "18d4fd3c6be0145f2775d87e15af794fc7ff3f172eed2c78cabedca8fcbc58609db04c13b1d2f7ac512d30a69d43a648029ab4b1ad74a289c18d6e27cffb17ed",
          "sha256": "e1ff9be503d7b8997bb6419406889a8a841322a2b8db54d477c8e059a72ad554",
          "sha1": "4827d974b6bdfd20cb8cb2dfcb5810686e8191da",
          "md5": "d173a3f159d7447dafc1b995af656bd7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "passkeys_android_release-1.0-javadoc.jar",
          "url": "passkeys_android_release-1.0-javadoc.jar",
          "size": 403696,
          "sha512": "a3eae398cad1c757b1fe3ed501c8d4de5effad415d35429719cf94f0da527e36dfd7ef33d73bed7a1374845fd1b145f487bad244e4a593094604200138aa45f0",
          "sha256": "6acae883999e1362e72a8f9ca6d1dfb79ecb148e0a9d61ac212051665e831953",
          "sha1": "8abb6ba02bb512b72fcf0f7630180d66b3af25c5",
          "md5": "98e53064a682ed829896fb0c450261a7"
        }
      ]
    }
  ]
}
