{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 13071,
          "sha512": "df8b10fba236e792f5c06df14b2166584740141ad8fea48cb4902d044a10dfacb23e1b313a8346c606d51f17679d5676caf805e87492de024232fe526704f2f7",
          "sha256": "1fc0761d23a1022fa0909894d6f630f67eaff13b1bcc6c8abf7abb8cdc50263a",
          "sha1": "5c008888f22989f95242b5bef57b773252a136ae",
          "md5": "10679e9b845000ba8ba638060debf242"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_profile-1.0.aar",
          "url": "path_provider_android_profile-1.0.aar",
          "size": 13071,
          "sha512": "df8b10fba236e792f5c06df14b2166584740141ad8fea48cb4902d044a10dfacb23e1b313a8346c606d51f17679d5676caf805e87492de024232fe526704f2f7",
          "sha256": "1fc0761d23a1022fa0909894d6f630f67eaff13b1bcc6c8abf7abb8cdc50263a",
          "sha1": "5c008888f22989f95242b5bef57b773252a136ae",
          "md5": "10679e9b845000ba8ba638060debf242"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_profile-1.0-sources.jar",
          "url": "path_provider_android_profile-1.0-sources.jar",
          "size": 4526,
          "sha512": "e5c851d74abe80cda84fa6edefecb314435cd71d84ae5fb47ee687a10da7ae90f1674b2ca676b2683792301033edae170753be825bd814053791e96689323caf",
          "sha256": "feff30f2abf50a7c185ff44f3f9047ada8d81f2bdb5ea4773c1aea80218e629d",
          "sha1": "27d930a8e3538f087253e61e2ddda54c99f84b9a",
          "md5": "848a06c2c0a9343517a4bbbb47c5c2f8"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_profile-1.0-javadoc.jar",
          "url": "path_provider_android_profile-1.0-javadoc.jar",
          "size": 298295,
          "sha512": "c055e822387d893b9aba9eec615eef941fabb31ce8f3ab20c5cad99999ee2e2d8fc46b2991887fd7009b684a3b6f5fdb396c18e097da6b06a6c77b5dd80fe974",
          "sha256": "c5f7af539fa83c50caa8d4ee41409967697c465379ac480b935c74b9f869a2cd",
          "sha1": "7ec9de42bfdfdfd07fe0d2a8d755f10110024a84",
          "md5": "bed8f30a7844f644488636fad955e8c6"
        }
      ]
    }
  ]
}
