// Autogenerated from Pigeon (v26.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")


import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object ApiPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a is ByteArray && b is ByteArray) {
        return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
        return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
        return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
        return a.contentEquals(b)
    }
    if (a is Array<*> && b is Array<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is List<*> && b is List<*>) {
      return a.size == b.size &&
          a.indices.all{ deepEquals(a[it], b[it]) }
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      return a.size == b.size && a.all {
          (b as Map<Any?, Any?>).containsKey(it.key) &&
          deepEquals(it.value, b[it.key])
      }
    }
    return a == b
  }
      
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

enum class ManiEnvironment(val raw: Int) {
  DEV(0),
  PROD(1);

  companion object {
    fun ofRaw(raw: Int): ManiEnvironment? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class ManiResidentType(val raw: Int) {
  RESIDENT(0),
  NON_RESIDENT(1);

  companion object {
    fun ofRaw(raw: Int): ManiResidentType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class DesignVariant(val raw: Int) {
  MANI(0),
  SMARTBANK(1),
  BRB(2),
  MKB(3);

  companion object {
    fun ofRaw(raw: Int): DesignVariant? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class CancelReason(val raw: Int) {
  USER_CANCELLED(0),
  INVALID_PHONE_NUMBER(1);

  companion object {
    fun ofRaw(raw: Int): CancelReason? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class Token (
  val accessToken: String? = null,
  val refreshToken: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): Token {
      val accessToken = pigeonVar_list[0] as String?
      val refreshToken = pigeonVar_list[1] as String?
      return Token(accessToken, refreshToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accessToken,
      refreshToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is Token) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}

/** Generated class from Pigeon that represents data sent in messages. */
data class HostInfo (
  val paymentSystemId: String? = null,
  val locale: String? = null,
  val pinfl: String? = null,
  val phoneNumber: String,
  val lastLogin: String? = null,
  val environment: ManiEnvironment? = null,
  val residentType: ManiResidentType? = null,
  val designVariant: DesignVariant? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): HostInfo {
      val paymentSystemId = pigeonVar_list[0] as String?
      val locale = pigeonVar_list[1] as String?
      val pinfl = pigeonVar_list[2] as String?
      val phoneNumber = pigeonVar_list[3] as String
      val lastLogin = pigeonVar_list[4] as String?
      val environment = pigeonVar_list[5] as ManiEnvironment?
      val residentType = pigeonVar_list[6] as ManiResidentType?
      val designVariant = pigeonVar_list[7] as DesignVariant?
      return HostInfo(paymentSystemId, locale, pinfl, phoneNumber, lastLogin, environment, residentType, designVariant)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      paymentSystemId,
      locale,
      pinfl,
      phoneNumber,
      lastLogin,
      environment,
      residentType,
      designVariant,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other !is HostInfo) {
      return false
    }
    if (this === other) {
      return true
    }
    return ApiPigeonUtils.deepEquals(toList(), other.toList())  }

  override fun hashCode(): Int = toList().hashCode()
}
private open class ApiPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ManiEnvironment.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ManiResidentType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          DesignVariant.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          CancelReason.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          Token.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          HostInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ManiEnvironment -> {
        stream.write(129)
        writeValue(stream, value.raw)
      }
      is ManiResidentType -> {
        stream.write(130)
        writeValue(stream, value.raw)
      }
      is DesignVariant -> {
        stream.write(131)
        writeValue(stream, value.raw)
      }
      is CancelReason -> {
        stream.write(132)
        writeValue(stream, value.raw)
      }
      is Token -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is HostInfo -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class ManiAuthApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by ManiAuthApi. */
    val codec: MessageCodec<Any?> by lazy {
      ApiPigeonCodec()
    }
  }
  fun send(hostInfoArg: HostInfo, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.mani_auth.ManiAuthApi.send$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(hostInfoArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(ApiPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface HostAppApi {
  fun cancel(reason: CancelReason)
  fun authSuccess(token: Token)

  companion object {
    /** The codec used by HostAppApi. */
    val codec: MessageCodec<Any?> by lazy {
      ApiPigeonCodec()
    }
    /** Sets up an instance of `HostAppApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: HostAppApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mani_auth.HostAppApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val reasonArg = args[0] as CancelReason
            val wrapped: List<Any?> = try {
              api.cancel(reasonArg)
              listOf(null)
            } catch (exception: Throwable) {
              ApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.mani_auth.HostAppApi.authSuccess$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val tokenArg = args[0] as Token
            val wrapped: List<Any?> = try {
              api.authSuccess(tokenArg)
              listOf(null)
            } catch (exception: Throwable) {
              ApiPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
