{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.uzinfocom.myid",
    "module": "myid_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.13"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "myid_debug-1.0.aar",
          "url": "myid_debug-1.0.aar",
          "size": 17583,
          "sha512": "6ff0bdb8c561593fff8c9e975f18dfd7278ee4ffcf155231426b97c20de61ff80549bdffe8fbc641ed034abf2c386f5f9c4283766dbb5f8250cef04498988ab1",
          "sha256": "addcabfd4ad7bd2b809cc5b63d60db991b5e9d305a3abb90c9369737cbfcb910",
          "sha1": "4c01b77bf48c7cc1420782a1d485a5a241fe4622",
          "md5": "05c6b2cab45d0b4d282b37825715cbfb"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "uz.myid.sdk.capture",
          "module": "myid-capture-sdk-debug",
          "version": {
            "requires": "3.1.1"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-035316565ad77281a75305515e4682e6c4c6f7ca"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "myid_debug-1.0.aar",
          "url": "myid_debug-1.0.aar",
          "size": 17583,
          "sha512": "6ff0bdb8c561593fff8c9e975f18dfd7278ee4ffcf155231426b97c20de61ff80549bdffe8fbc641ed034abf2c386f5f9c4283766dbb5f8250cef04498988ab1",
          "sha256": "addcabfd4ad7bd2b809cc5b63d60db991b5e9d305a3abb90c9369737cbfcb910",
          "sha1": "4c01b77bf48c7cc1420782a1d485a5a241fe4622",
          "md5": "05c6b2cab45d0b4d282b37825715cbfb"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_debug-1.0-sources.jar",
          "url": "myid_debug-1.0-sources.jar",
          "size": 5024,
          "sha512": "8bfca27fe63e60f5900c6240c513a86aff730822a60a4888f3b645516a7b0915789ea856aa09024c0526f955a2592f2289699de0867f3ca301f17f93080bab05",
          "sha256": "a66ff14835924260b7b481a63ada8baf225d7c807b95bac9f3341497cd8b84fc",
          "sha1": "42956ae96bec056d53d13d309a7d4abc45292fb2",
          "md5": "00e3a2e2c41c8cb2f9921d627b3ab4c6"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_debug-1.0-javadoc.jar",
          "url": "myid_debug-1.0-javadoc.jar",
          "size": 277000,
          "sha512": "9d3f96af0880270ab9a270c470b474994902be1f2c3fe82a1fbd9dc4533cf531f382e69fa79824de492c6d38db994d0b32248c2ba5659632ed2aa2063d57d88a",
          "sha256": "8b2b52f9873bab2412f4868daea1a12ebbe2c8eaf693723a590390499d9afa46",
          "sha1": "b99b9af321db97078e38f7623036e8c6c03add31",
          "md5": "c133a8ad7a67c6bf013f22b9fb55e10f"
        }
      ]
    }
  ]
}
