{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.uzinfocom.myid",
    "module": "myid_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "myid_debug-1.0.aar",
          "url": "myid_debug-1.0.aar",
          "size": 21831,
          "sha512": "214f0c3f55e356e0e9a9aec85d6571c570a93279ecbc7e56f3d11feabe487c481306d739a6cb419d4b07adb48da6126338febbc77cc7483ff87fdf70dbfe53fb",
          "sha256": "b6d6fdc5fd7de86241e32d81da99b71994c55dab0c9b4f7a23403d715a08072f",
          "sha1": "c5bc1b508acb23e4f95a7e900f425386acff6ddb",
          "md5": "41194973472dbbbbce5e363071c710a6"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "uz.myid.sdk.capture",
          "module": "myid-capture-sdk",
          "version": {
            "requires": "2.3.7"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "myid_debug-1.0.aar",
          "url": "myid_debug-1.0.aar",
          "size": 21831,
          "sha512": "214f0c3f55e356e0e9a9aec85d6571c570a93279ecbc7e56f3d11feabe487c481306d739a6cb419d4b07adb48da6126338febbc77cc7483ff87fdf70dbfe53fb",
          "sha256": "b6d6fdc5fd7de86241e32d81da99b71994c55dab0c9b4f7a23403d715a08072f",
          "sha1": "c5bc1b508acb23e4f95a7e900f425386acff6ddb",
          "md5": "41194973472dbbbbce5e363071c710a6"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_debug-1.0-sources.jar",
          "url": "myid_debug-1.0-sources.jar",
          "size": 5249,
          "sha512": "3d2f2db46be3f5b3e3d01496b79c87be3bd1354d91436f7a919fd47e549dcb7db9ef08ea72bf4c4d83c78e76f87dae67d1ca4297b8fa5dc77f583a9bbbed5caa",
          "sha256": "592aeb24c7c2b98ee8df12e5eca8dd4b57d1454e87d0735f4c49a7ebcc833fdb",
          "sha1": "26a6d369412a1976ab3948b85363df91dab61dc7",
          "md5": "e6c12d131c40a7ef6fc0f5682e515995"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_debug-1.0-javadoc.jar",
          "url": "myid_debug-1.0-javadoc.jar",
          "size": 285781,
          "sha512": "2059bb5ca21d0de30b597ea3938d1fba67a67cfe8abdca004183dc572a205162a3cc53aa15c53ebb96e980485dad4e46c296c8bb499e8736c57a1cdeb83f6c15",
          "sha256": "4992e53c45b13af49417c2a325234478adcf956193f35df91ac81703f0b2db8c",
          "sha1": "8ee85756a7f423c78381d2693b59fbf6f6e3edd1",
          "md5": "c54fc4068a1d6166cae61db39ada2ba2"
        }
      ]
    }
  ]
}
