{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.uzinfocom.myid",
    "module": "myid_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "myid_debug-1.0.aar",
          "url": "myid_debug-1.0.aar",
          "size": 21845,
          "sha512": "d1a847ff17b586ac56b00f84e2998d479c606c05f2145df1450f37a22e66b376ba4d9326337023b2f24081797014bf9a0850b1c8561f02ee67ab08b1f2b471d5",
          "sha256": "0d0eaf9f929a9e017a25b9f5fe9aacace84d38641959dfe6a46f8406b53d99e3",
          "sha1": "b672a17ff4c3d824de26a2d267aaa969f4539f44",
          "md5": "ef7f53175d2fcbaff4d1e53b31f74cbf"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "uz.myid.sdk.capture",
          "module": "myid-capture-sdk-bundled",
          "version": {
            "requires": "2.3.5"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.8.22"
          }
        }
      ],
      "files": [
        {
          "name": "myid_debug-1.0.aar",
          "url": "myid_debug-1.0.aar",
          "size": 21845,
          "sha512": "d1a847ff17b586ac56b00f84e2998d479c606c05f2145df1450f37a22e66b376ba4d9326337023b2f24081797014bf9a0850b1c8561f02ee67ab08b1f2b471d5",
          "sha256": "0d0eaf9f929a9e017a25b9f5fe9aacace84d38641959dfe6a46f8406b53d99e3",
          "sha1": "b672a17ff4c3d824de26a2d267aaa969f4539f44",
          "md5": "ef7f53175d2fcbaff4d1e53b31f74cbf"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_debug-1.0-sources.jar",
          "url": "myid_debug-1.0-sources.jar",
          "size": 5249,
          "sha512": "3d2f2db46be3f5b3e3d01496b79c87be3bd1354d91436f7a919fd47e549dcb7db9ef08ea72bf4c4d83c78e76f87dae67d1ca4297b8fa5dc77f583a9bbbed5caa",
          "sha256": "592aeb24c7c2b98ee8df12e5eca8dd4b57d1454e87d0735f4c49a7ebcc833fdb",
          "sha1": "26a6d369412a1976ab3948b85363df91dab61dc7",
          "md5": "e6c12d131c40a7ef6fc0f5682e515995"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_debug-1.0-javadoc.jar",
          "url": "myid_debug-1.0-javadoc.jar",
          "size": 285781,
          "sha512": "2059bb5ca21d0de30b597ea3938d1fba67a67cfe8abdca004183dc572a205162a3cc53aa15c53ebb96e980485dad4e46c296c8bb499e8736c57a1cdeb83f6c15",
          "sha256": "4992e53c45b13af49417c2a325234478adcf956193f35df91ac81703f0b2db8c",
          "sha1": "8ee85756a7f423c78381d2693b59fbf6f6e3edd1",
          "md5": "c54fc4068a1d6166cae61db39ada2ba2"
        }
      ]
    }
  ]
}
