{
  "formatVersion": "1.1",
  "component": {
    "group": "com.corbado.passkeys_doctor",
    "module": "passkeys_doctor_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        }
      ],
      "files": [
        {
          "name": "passkeys_doctor_release-1.0.aar",
          "url": "passkeys_doctor_release-1.0.aar",
          "size": 6831,
          "sha512": "80566bbe6cd83eb574715c8ee955bf26bb021cffcf0eb7883f2ef75aa8d80e364b1bb77b7005785c0e8649d5a59771668f314912fde869bcb78128776bc80985",
          "sha256": "0afc9c61db6520384159721bad28b870f40f64985fbb766af5ad0e56fab6abf7",
          "sha1": "0255e055aa1db89ea1e9a55911e763ff2fdc8b3c",
          "md5": "b2162b8ef5e53fac9fc874b1e2838e62"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "passkeys_doctor_release-1.0.aar",
          "url": "passkeys_doctor_release-1.0.aar",
          "size": 6831,
          "sha512": "80566bbe6cd83eb574715c8ee955bf26bb021cffcf0eb7883f2ef75aa8d80e364b1bb77b7005785c0e8649d5a59771668f314912fde869bcb78128776bc80985",
          "sha256": "0afc9c61db6520384159721bad28b870f40f64985fbb766af5ad0e56fab6abf7",
          "sha1": "0255e055aa1db89ea1e9a55911e763ff2fdc8b3c",
          "md5": "b2162b8ef5e53fac9fc874b1e2838e62"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "passkeys_doctor_release-1.0-sources.jar",
          "url": "passkeys_doctor_release-1.0-sources.jar",
          "size": 3161,
          "sha512": "b19f9bba1e42c19c684c8a409ee17411263952c49ba97b34fe8e28b62b4dd7fbb227f57bdfa2c9bcae37bc7c560a0a36c1281af59b1b5e7b46644998291c6ab7",
          "sha256": "c8bc5f63d2412ca33deba455847b2539cabfd1ab451e7d902c32bec7f4d95fd2",
          "sha1": "18920dee025953c2194f9532cceb5059f6450ed1",
          "md5": "0cda1aa954dbd58a77a667ac2ad1c9b3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "passkeys_doctor_release-1.0-javadoc.jar",
          "url": "passkeys_doctor_release-1.0-javadoc.jar",
          "size": 283705,
          "sha512": "144dd2e4e4374677381bb9a015d78faa0d49107b88a86e11a29813863165b815b2fedcafd3a8758ba61fdace9c26ae0c9fd2634ba64ef9e7adabc73e63913d5e",
          "sha256": "e956e24469bb7f848a20880a74a2d9e57a985c5940fd60457fcca4b2fb556e41",
          "sha1": "e95c73796d64f422bd43cbb0fbe9a35242309b6c",
          "md5": "60a5a9ed5b7856a5df71fec2d0c7ca28"
        }
      ]
    }
  ]
}
