{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.pathprovider",
    "module": "path_provider_android_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 13569,
          "sha512": "92e835e59ed8685dad53dd48f01f62a9dd45d65ebd3f42118ade25172231accf6b3b690256d64590bc49d919435c3bd6b2a3ebcea9334b8f4471a9ff655db06a",
          "sha256": "415fdef3f68a645d6fe549d9a6b0152b73a202ec6070cdd0dd37e9cfbc11284d",
          "sha1": "a4615f23d362c4c329c82003ad6163a2f9a043d9",
          "md5": "5baa800e991b30bf81d54b5f97adcb67"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "path_provider_android_debug-1.0.aar",
          "url": "path_provider_android_debug-1.0.aar",
          "size": 13569,
          "sha512": "92e835e59ed8685dad53dd48f01f62a9dd45d65ebd3f42118ade25172231accf6b3b690256d64590bc49d919435c3bd6b2a3ebcea9334b8f4471a9ff655db06a",
          "sha256": "415fdef3f68a645d6fe549d9a6b0152b73a202ec6070cdd0dd37e9cfbc11284d",
          "sha1": "a4615f23d362c4c329c82003ad6163a2f9a043d9",
          "md5": "5baa800e991b30bf81d54b5f97adcb67"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_debug-1.0-sources.jar",
          "url": "path_provider_android_debug-1.0-sources.jar",
          "size": 4538,
          "sha512": "c698c71eea503ece5d67615001ff35e3c5274b60faa5d7ee75b290b406edd4dab9a6c9fa3bf77ee9225065e9c451008d1742313803304be955956e390c748600",
          "sha256": "bb2877d8bbd2a061483fa70dd56c090c4e4e3a202d0ab773e52e21ebf50b2b9c",
          "sha1": "fc8e00d608ec4948b012562cf1b00bac5f2407cc",
          "md5": "bbce3e9a2ca95177d9b7e0b8bdc602e9"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "path_provider_android_debug-1.0-javadoc.jar",
          "url": "path_provider_android_debug-1.0-javadoc.jar",
          "size": 298287,
          "sha512": "fbeb06588c1303c87d3d9f5306fdbdcef879d21a88216a4248c6cf526df982927e2730aaf2467cf7d17cd2c6350e6f3be7fafa719b6c87aa4967505ab84b30f9",
          "sha256": "5f20797356b17149b18d778fb7be104e51a4896b2947f390924430d3a5c00987",
          "sha1": "c565da3c181a798969f45f84514bd0df1e21f06c",
          "md5": "904cf185d8f3e593b78742c876225876"
        }
      ]
    }
  ]
}
