{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.mani_auth",
    "module": "flutter_profile",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "profileVariantProfileApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "uz.uzinfocom.myid",
          "module": "myid_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 16427375,
          "sha512": "3b04b9b8ec62253180d891b527ccb82cbf5c76476b8a7c357f7578209688fbd16431f07d8844559fdbf5ba33b5bbf23f067e786b48e5b6192cdf2a6d1db60320",
          "sha256": "161c6f0c09c4e7f49fd2e0761edcf34ba02c1f5c69404fdc1c1fdc2c9634bbaf",
          "sha1": "527139ff842300e7e701532dbe69ab8452e0558c",
          "md5": "6d12514d6359abbccf5a673ed7112c8b"
        }
      ]
    },
    {
      "name": "profileVariantProfileRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_profile",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "uz.uzinfocom.myid",
          "module": "myid_profile",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_profile-1.0.aar",
          "url": "flutter_profile-1.0.aar",
          "size": 16427375,
          "sha512": "3b04b9b8ec62253180d891b527ccb82cbf5c76476b8a7c357f7578209688fbd16431f07d8844559fdbf5ba33b5bbf23f067e786b48e5b6192cdf2a6d1db60320",
          "sha256": "161c6f0c09c4e7f49fd2e0761edcf34ba02c1f5c69404fdc1c1fdc2c9634bbaf",
          "sha1": "527139ff842300e7e701532dbe69ab8452e0558c",
          "md5": "6d12514d6359abbccf5a673ed7112c8b"
        }
      ]
    },
    {
      "name": "profileVariantProfileSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-sources.jar",
          "url": "flutter_profile-1.0-sources.jar",
          "size": 1770,
          "sha512": "4a7ebaa05e61892d306b3a3b26416a1fdee7602dc5a0635a4522c3d1960fe02eb54f73172eff47e570eceb28cd59c4513a129e6ac0450ea78adaffd00458a39d",
          "sha256": "8d13f559797f3835d6c27acb7a7e14a5fa2c239eff43308af39c6508656541ff",
          "sha1": "0dcec69f3c95f44acbadc8523e936fa73a64003d",
          "md5": "fc7ff19a4f3d4f67f93cbb64999c58d0"
        }
      ]
    },
    {
      "name": "profileVariantProfileJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_profile-1.0-javadoc.jar",
          "url": "flutter_profile-1.0-javadoc.jar",
          "size": 269302,
          "sha512": "d12e16ef73d41374d8e530f042cca6f90771abaa21cf579fad10a87d395be3b2006fc463e46930e7969831b74a88e0a7e5c67cb89bf4691a5b50bfb18b1485ca",
          "sha256": "5397106a1c5dcaedc308e15cc0a9f1be8d9af57d6dc6e5d89bd230a99c193760",
          "sha1": "370874095df99f8813c9a12b916a036af51fd0c9",
          "md5": "4cdd291cf61f790ddd1d70ddbe8d2f10"
        }
      ]
    }
  ]
}
