{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.uzinfocom.myid",
    "module": "myid_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "myid_release-1.0.aar",
          "url": "myid_release-1.0.aar",
          "size": 17001,
          "sha512": "8e4bae38cfe9b47f67f09d613ef4773a853947a25ae913a449648ed7e3cf4ec750358728cacf9bd9bc0628327dd54d03a0d49411c19f3dd003a47fca5ac0fe8e",
          "sha256": "2ccae32fa07f2a43f0256a2dd79ea61e05e89f869301bcd3fc66e1e6c919ecff",
          "sha1": "4a3fbd0701d61f4e1599ba7e225cbb6a117911b0",
          "md5": "51e189820966cbe3b43dab63ca5e99c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "uz.myid.sdk.capture",
          "module": "myid-capture-sdk",
          "version": {
            "requires": "3.1.4"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-425cfb54d01a9472b3e81d9e76fd63a4a44cfbcb"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "myid_release-1.0.aar",
          "url": "myid_release-1.0.aar",
          "size": 17001,
          "sha512": "8e4bae38cfe9b47f67f09d613ef4773a853947a25ae913a449648ed7e3cf4ec750358728cacf9bd9bc0628327dd54d03a0d49411c19f3dd003a47fca5ac0fe8e",
          "sha256": "2ccae32fa07f2a43f0256a2dd79ea61e05e89f869301bcd3fc66e1e6c919ecff",
          "sha1": "4a3fbd0701d61f4e1599ba7e225cbb6a117911b0",
          "md5": "51e189820966cbe3b43dab63ca5e99c7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_release-1.0-sources.jar",
          "url": "myid_release-1.0-sources.jar",
          "size": 5049,
          "sha512": "2e34b7620f8f5115a4f126606fa80f93246d9093c40c09593f6ecbb7e72a568ac27efedf678bb0f7599eee36728b40cff5c2182fa0048ad179a5573f4223bed5",
          "sha256": "e927cf60c11a5d5f300fc73511c38461915c05bc73d22e1daca638bef55f93ab",
          "sha1": "53c9efff1cd3cbd54f54ed184b67545830a3204c",
          "md5": "34d297544b2483a35bd3b869f667f240"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_release-1.0-javadoc.jar",
          "url": "myid_release-1.0-javadoc.jar",
          "size": 277000,
          "sha512": "9d3f96af0880270ab9a270c470b474994902be1f2c3fe82a1fbd9dc4533cf531f382e69fa79824de492c6d38db994d0b32248c2ba5659632ed2aa2063d57d88a",
          "sha256": "8b2b52f9873bab2412f4868daea1a12ebbe2c8eaf693723a590390499d9afa46",
          "sha1": "b99b9af321db97078e38f7623036e8c6c03add31",
          "md5": "c133a8ad7a67c6bf013f22b9fb55e10f"
        }
      ]
    }
  ]
}
