{
  "formatVersion": "1.1",
  "component": {
    "group": "uz.uzinfocom.myid",
    "module": "myid_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "myid_release-1.0.aar",
          "url": "myid_release-1.0.aar",
          "size": 16420,
          "sha512": "789685e209ae39dc1f9f856aee63a31a8ada5b19eac72b910270536ce90c7faed710c1ebbb318284adbf2abac208574a153b498379469a45f8bb9b80540aacc0",
          "sha256": "873a5465bfb23add4ce7233a7c0f2391b76c85149a462f2055e609bf3670d24e",
          "sha1": "d949454e1793e003fbdebd57f9e30d9c4efdd01b",
          "md5": "23ae746b4033dbf82be146663ab9e000"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-1e9a811bf8e70466596bcf0ea3a8b5adb5f17f7f"
          }
        },
        {
          "group": "uz.myid.sdk.capture",
          "module": "myid-capture-sdk",
          "version": {
            "requires": "2.4.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "myid_release-1.0.aar",
          "url": "myid_release-1.0.aar",
          "size": 16420,
          "sha512": "789685e209ae39dc1f9f856aee63a31a8ada5b19eac72b910270536ce90c7faed710c1ebbb318284adbf2abac208574a153b498379469a45f8bb9b80540aacc0",
          "sha256": "873a5465bfb23add4ce7233a7c0f2391b76c85149a462f2055e609bf3670d24e",
          "sha1": "d949454e1793e003fbdebd57f9e30d9c4efdd01b",
          "md5": "23ae746b4033dbf82be146663ab9e000"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_release-1.0-sources.jar",
          "url": "myid_release-1.0-sources.jar",
          "size": 4922,
          "sha512": "f18705ed4ae1fc7d3fa8e00adc5af3f26a5898398d6d34f4f2a9529a7681fb73c9b7284acd5de6e762c92bb067dfca773007b1157ee469dcc7114e153b5fb962",
          "sha256": "8a56adebd97250d35477b33b5e82c794faabfdc04873c74efc38e7bbeb8439a7",
          "sha1": "dbf89de8c1915656051966ded3515dc54bf00ad6",
          "md5": "f07251c88ac7eb1b0c25cfa032990e81"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "myid_release-1.0-javadoc.jar",
          "url": "myid_release-1.0-javadoc.jar",
          "size": 277147,
          "sha512": "2c6dba2869bfbacec20a47555ef06d8322a7481b86312be75a4ff9461a151a3ccd66767e6ab42be479d5dc6b0d4b89a09443f9f27d9671ec8f1f8ee81b57ed3c",
          "sha256": "484316d0976d0956ec9685c5fa3fbb940214c306e7971381a4c85addfa2dddb4",
          "sha1": "876b6a92fe4b35e27b41d8646aed05191f1f21de",
          "md5": "d2cf2d5494e263d9bde784f2dea9484a"
        }
      ]
    }
  ]
}
