{
  "formatVersion": "1.1",
  "component": {
    "group": "com.example.mani_auth",
    "module": "flutter_debug",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.5"
    }
  },
  "variants": [
    {
      "name": "debugVariantDebugApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "uz.uzinfocom.myid",
          "module": "myid_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 24357038,
          "sha512": "df58a5a4a5c3775bf922009512fb84671b83630e06071a2e99a8575b61abc1cc037754ba0df3de741fd5a5de1d7a3028fae5ffe96af7077a2f6d6b7a5a3f1f9f",
          "sha256": "28af0826c1d95cfe6adc97895b78e6df27e4497d327f935afa7787c3fb5ffb3b",
          "sha1": "b9ac6621bbe1d545b0583f27a689ca817c3f71fd",
          "md5": "12b9edb4e4afab2be7862c03d777f7d7"
        }
      ]
    },
    {
      "name": "debugVariantDebugRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_debug",
          "version": {
            "requires": "1.0.0-36335019a8eab588c3c2ea783c618d90505be233"
          }
        },
        {
          "group": "uz.uzinfocom.myid",
          "module": "myid_debug",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_debug-1.0.aar",
          "url": "flutter_debug-1.0.aar",
          "size": 24357038,
          "sha512": "df58a5a4a5c3775bf922009512fb84671b83630e06071a2e99a8575b61abc1cc037754ba0df3de741fd5a5de1d7a3028fae5ffe96af7077a2f6d6b7a5a3f1f9f",
          "sha256": "28af0826c1d95cfe6adc97895b78e6df27e4497d327f935afa7787c3fb5ffb3b",
          "sha1": "b9ac6621bbe1d545b0583f27a689ca817c3f71fd",
          "md5": "12b9edb4e4afab2be7862c03d777f7d7"
        }
      ]
    },
    {
      "name": "debugVariantDebugSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-sources.jar",
          "url": "flutter_debug-1.0-sources.jar",
          "size": 1769,
          "sha512": "45236c17f197083f665df6c969887d964fa72fb74ab4378083476692311aaf9841cb2d53f8f92dc65a710ca7c74ea9e29e4cd2c1d579188d927c611fc3f8cbef",
          "sha256": "d4c0bda03847437d0e2341a2ffc055e891fdd975fb7ecafc251b7b2b20670e20",
          "sha1": "421d3b6272f3e3f3afebd05ed484d78ef852e108",
          "md5": "3ff3b72214a88638d511e303eadbc832"
        }
      ]
    },
    {
      "name": "debugVariantDebugJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_debug-1.0-javadoc.jar",
          "url": "flutter_debug-1.0-javadoc.jar",
          "size": 269302,
          "sha512": "d12e16ef73d41374d8e530f042cca6f90771abaa21cf579fad10a87d395be3b2006fc463e46930e7969831b74a88e0a7e5c67cb89bf4691a5b50bfb18b1485ca",
          "sha256": "5397106a1c5dcaedc308e15cc0a9f1be8d9af57d6dc6e5d89bd230a99c193760",
          "sha1": "370874095df99f8813c9a12b916a036af51fd0c9",
          "md5": "4cdd291cf61f790ddd1d70ddbe8d2f10"
        }
      ]
    }
  ]
}
